[book]
authors = ["ahmadrosid"]
language = "en"
multilingual = false
src = "src"
title = "Personal Wiki"

[build]
build-dir="../public/wiki"

[output.html]
site-url="wiki"
default-theme="light"
additional-css=["custom.css"]

